apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: k8s-bigip-ctlr
  name: k8s-bigip-ctlr
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr
      name: k8s-bigip-ctlr
    spec:
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=10.17.20.191
        - --insecure
        - --bigip-partition=kubernetes
        - --pool-member-type=cluster
        - --openshift-sdn-name=/Common/openshift_vxlan
        - --default-ingress-ip=10.17.12.11
        - --default-client-ssl=/Common/star.apps.f5demo.com
        - --default-server-ssl=/Common/openshift_default
        - --manage-routes=true
        - --route-label=bigipa
        - --route-vserver-addr=10.17.12.24
        - --agent=as3
        - --as3-validation=false
        - --log-as3-response=true
        - --override-as3-declaration=default/f5-route-vs-override
        - --log-level=INFO
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login
        image: f5networks/k8s-bigip-ctlr:1.13.0
        name: k8s-bigip-ctlr
      imagePullSecrets:
      - name: bigip-login
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
