apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${AppName}
  namespace: ${Namespace}
  labels:
    app: ${AppName}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${AppName}
  template:
    metadata:
      labels:
        app: ${AppName}
    spec:
      containers:
      - name: ${AppName}
        image: f5devcentral/f5-demo-app:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0

---

kind: Service
apiVersion: v1
metadata:
  name: ${AppName}-service
  namespace: ${Namespace}
  labels:
    cis.f5.com/as3-tenant: as3
    cis.f5.com/as3-app: ${AppName}
    cis.f5.com/as3-pool: webpool
spec:
  selector:
    app: ${AppName}
  ports:
  - protocol: TCP
    port: 80
