kind: ConfigMap
apiVersion: v1
metadata:
  name: ${AppName}-as3
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "d492687a-bd1d-478d-987b-9590253c5071",
        "label": "Sample AS3 with individual ASM policy",
        "remark": "Simple HTTP Service with ASM policy",
        "as3": {
          "class": "Tenant"
        }
      }
    }