kind: ConfigMap
apiVersion: v1
metadata:
  name: ${AppName}-as3
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "d492687a-bd1d-478d-987b-9590253c5071",
        "label": "Sample AS3 with predefined ASM policy",
        "remark": "Simple HTTP Service with ASM policy",
        "as3": {
          "class": "Tenant",
          "${AppName}": {
            "class": "Application",
            "template": "https",
            "serviceMain": {
              "class": "Service_HTTPS",
              "virtualAddresses": [
                 "${IPaddr}"
              ],
              "pool": "webpool",
              "policyWAF": {
                "bigip": "/Common/FundamentalPolicyForLinuxApacheMySQL"
              },
              "securityLogProfiles": [
                {"bigip": "/Common/Log all requests"}
              ],
              "profileHTTP": { "use": "http_prof_mid_security" },
              "profileHTTPAcceleration": { "use": "my_caching" },
              "profileHTTPCompression": { "use":"my_compression" },
              "redirect80": true,
              "serverTLS": { "bigip": "/Common/star.f5demo.com" }
            },
            "webpool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "reselectTries": 1,
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "http_prof_mid_security": {
              "class": "HTTP_Profile",
              "proxyType": "reverse",
              "allowedResponseHeaders": [
                "content-type",
                "set-cookie",
                "location",
                "date",
                "expires",
                "cache-control",
                "pragma",
                "vary",
                "content-encoding",
                "keep-alive",
                "connection" 
              ],
              "fallbackRedirect": "https://www.f5.com",
              "xForwardedFor": true
            },
            "my_caching": {
              "class": "HTTP_Acceleration_Profile",
              "parentProfile": { "bigip": "/Common/webacceleration" },
              "maximumObjectSize": 200000,
              "maximumEntries": 5000,
              "maximumAge": 120
            },
            "my_compression": {
              "class": "HTTP_Compress",
              "minimumSize": 2000
            }
          }
        }
      }
    }
