kind: ConfigMap
apiVersion: v1
metadata:
  name: simpleapp-vs
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "kubernetes",
          "virtualAddress": {
            "bindAddr": "${IPaddr}",
            "port": 443
          },
          "sslProfile": {
            "f5ProfileName": "/Common/clientssl"
          }
        },
        "backend": {
          "serviceName": "simpleapp-service",
          "servicePort": 80,
          "healthMonitors":
            [
              {
                "protocol": "http",
                "interval": 3,
                "timeout": 10,
                "send": "GET / HTTP/1.1\r\nHost: 10.1.10.11",
                "recv": "Request Headers"
              }
            ]
        }
      }
    }
