kind: ConfigMap
apiVersion: v1
metadata:
  name: ${AppName}-as3
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "d492687a-bd1d-478d-987b-9590253c5071",
        "label": "Sample AS3 with predefined ASM policy",
        "remark": "Simple HTTP Service with ASM policy",
        "as3": {
          "class": "Tenant",
          "${AppName}": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                 "${IPaddr}"
              ],
              "pool": "webpool",
              "policyWAF": {
                "bigip": "/Common/FundamentalPolicyForLinuxApacheMySQL"
              },
              "securityLogProfiles": [
                {"bigip": "/Common/Log all requests"}
              ]
            },
            "webpool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            }
          }
        }
      }
    }
