---
- name: Manage analytics profile
  bigip_profile_analytics:
    provider: "{{ provider }}"
    partition: "{{ bigip_partition }}"
    name: "{{profile_name}}_analytics"
    collect_geo: yes
    collect_ip: yes
    collect_max_tps_and_throughput: yes
    collect_user_agent: yes
    collect_url: yes
    state: "{{ state }}"
  delegate_to: localhost
...
