---
- name: Manage VIP
  bigip_virtual_server:
    provider: "{{ provider }}"
    partition: "/kubernetes"
    name: ansible/vip-1
    destination: 10.1.10.14
    port: 80
    snat: Automap
    pool: /kubernetes/cfgmap_default_app4ansible-vs_app4ansible-service
    profiles:
      - http
    state: "{{ state }}"
  delegate_to: localhost
...
