---
#############
# Add objects
#############
- include: bigip_profile_http/manage_http_profile.yaml
  when: state == "present"

- include: bigip_profile_analytics/manage_bigip_profile_analytics.yaml
  when: state == "present"

- include: bigip_asm_policy_import/manage_bigip_asm_policy_import.yaml
  when: state == "present"

- include: bigip_virtual_server/manage_vip.yaml
  when: state == "present"

################
# Remove objects
################
- include: bigip_profile_http/manage_http_profile.yaml
  when: state == "absent"

- include: bigip_profile_analytics/manage_bigip_profile_analytics.yaml
  when: state == "absent"

- include: bigip_virtual_server/manage_vip.yaml
  when: state == "absent"
...
