- name: Create VIP for Kubernetes
  hosts: boarder_bigips
  connection: local

  vars:
    provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: no
      server_port: 443

  tasks:
    - name: Create VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        partition: "/kubernetes"
        name: ansible/vip-1
        destination: 10.1.10.14
        port: 80
        snat: Automap
        pool: /kubernetes/cfgmap_default_app4ansible-vs_app4ansible-service
        profiles:
          - http
      delegate_to: localhost
