---
- name: Create VIP for Kubernetes
  hosts: boarder_bigips
  connection: local
  gather_facts: False

  vars:
    provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: no
      server_port: 443

  roles:
    - SimpleVIP
...
